spring.datasource.url=jdbc:h2:mem:mscontractsdb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# directory where generated PDFs are stored (relative to project root)
contracts.storage.dir=contracts

# server port (optional)
server.port=8083

