#!/usr/bin/env bash
# Generates the production .env. Secrets are minted here and never leave the
# host; only the values we cannot invent (DuckDNS token, SMTP, Vercel origin)
# are prompted for.
set -euo pipefail

cd "$(dirname "$0")/.."

if [ -f .env ]; then
  read -rp ".env already exists. Overwrite it? [y/N] " ans
  [[ "$ans" =~ ^[Yy]$ ]] || { echo "Aborted."; exit 0; }
  cp .env ".env.bak.$(date +%s)"
  echo "Previous file kept as .env.bak.*"
fi

ask() {  # ask VAR "prompt" [default]
  local __var=$1 __prompt=$2 __default=${3:-} __val
  if [ -n "$__default" ]; then
    read -rp "$__prompt [$__default]: " __val
    __val=${__val:-$__default}
  else
    while [ -z "${__val:-}" ]; do read -rp "$__prompt: " __val; done
  fi
  printf -v "$__var" '%s' "$__val"
}

ask_secret() {
  local __var=$1 __prompt=$2 __val
  while [ -z "${__val:-}" ]; do read -rsp "$__prompt: " __val; echo; done
  printf -v "$__var" '%s' "$__val"
}

echo "--- Values only you know ---"
ask        DUCKDNS_TOKEN        "DuckDNS token"
ask        CORS_ALLOWED_ORIGINS "Frontend origin on Vercel (no trailing slash)" "https://the-circle.vercel.app"
ask        MAIL_HOST            "SMTP host" "smtp.gmail.com"
ask        MAIL_PORT            "SMTP port" "587"
ask        MAIL_USER            "SMTP user"
ask_secret MAIL_PASSWORD        "SMTP password (Gmail app password, 16 chars)"
ask        MAIL_FROM            "From address" "$MAIL_USER"

umask 077
cat > .env <<ENVEOF
# Generated by deploy/gen-env.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Secrets below are random per host. Do not commit this file.

DB_USER=thecircle
DB_PASSWORD=$(openssl rand -hex 24)
DB_NAME=thecircledb

JWT_SECRET=$(openssl rand -base64 48 | tr -d '\n')

USERS_INTERNAL_KEY=$(openssl rand -hex 32)
CATALOG_INTERNAL_KEY=$(openssl rand -hex 32)
CONTRACTS_INTERNAL_KEY=$(openssl rand -hex 32)
NOTIFICATIONS_INTERNAL_KEY=$(openssl rand -hex 32)

CORS_ALLOWED_ORIGINS=$CORS_ALLOWED_ORIGINS
DUCKDNS_TOKEN=$DUCKDNS_TOKEN

MAIL_HOST=$MAIL_HOST
MAIL_PORT=$MAIL_PORT
MAIL_USER=$MAIL_USER
MAIL_PASSWORD=$MAIL_PASSWORD
MAIL_FROM=$MAIL_FROM
ENVEOF

chmod 600 .env
echo
echo ".env written (mode 600). Next: ./deploy/up.sh"
