server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: when_authorized
    gateway:
      enabled: true

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: ms-users-auth
          uri: ${MS_USERS_URL:http://localhost:8081}
          predicates:
            - Path=/api/auth/**
        - id: ms-users
          uri: ${MS_USERS_URL:http://localhost:8081}
          predicates:
            - Path=/api/users/**
        - id: ms-catalog
          uri: ${MS_CATALOG_URL:http://localhost:8082}
          predicates:
            - Path=/api/catalog/**
        - id: ms-contracts
          uri: ${MS_CONTRACTS_URL:http://localhost:8083}
          predicates:
            - Path=/api/contracts/**
        - id: ms-gamification
          uri: ${MS_GAMIFICATION_URL:http://localhost:8084}
          predicates:
            - Path=/api/gamification/**

logging:
  level:
    org.springframework.cloud.gateway: ${GATEWAY_LOG_LEVEL:INFO}
    reactor.netty.http.client: ${REACTOR_NETTY_HTTP_CLIENT_LOG_LEVEL:INFO}
    reactor.netty.http.server: ${REACTOR_NETTY_HTTP_SERVER_LOG_LEVEL:INFO}